#!/bin/sh

# Quarkdown launcher (Nix-wrapped)
# Generated by dots - APP_HOME and JAVA_CMD are substituted at build time

APP_HOME=@APP_HOME@
JAVACMD=@JAVA_CMD@
CLASSPATH="$APP_HOME/lib/*"

if [ -n "$QD_NPM_PREFIX" ]; then
  export NODE_PATH="$QD_NPM_PREFIX/node_modules"
fi

# Linux browser detection
export QD_NO_SANDBOX=true
if command -v google-chrome > /dev/null; then
  export BROWSER_CHROME="$(command -v google-chrome)"
fi
if command -v chromium-browser > /dev/null; then
  export BROWSER_CHROMIUM="$(command -v chromium-browser)"
fi
if command -v chromium > /dev/null; then
  export BROWSER_CHROMIUM="$(command -v chromium)"
fi
if command -v firefox > /dev/null; then
  export BROWSER_FIREFOX="$(command -v firefox)"
fi

exec "$JAVACMD" \
  -classpath "$CLASSPATH" \
  com.quarkdown.cli.QuarkdownCliKt \
  "$@"
